### ISSUE TITLE
[Feat/Auth-service] Companies CRUD 개발

### ISSUE THREAD

**Issue by DISNOTACAT** [Sparta-mosaic/msa-mosaic#1]
## Description
업체 데이터 관련 CRUD 를 개발합니다.

## To-do

- [x] Users, Compaies Entity
- [x] 업체 더미 생성
- [x] 업체 서치
- [x] 업체 정보 추가하기
- [x] 업체 정보 수정하기
- [x] 업체 삭제하기

## Related issues

Related to: #이슈번호
