### ISSUE TITLE
[Feat/hub-service] 허브 생성 기능 개발

### ISSUE THREAD

**Issue by Hut234** [Sparta-mosaic/msa-mosaic#2]
## Description
- 허브 생성 기능 개발

## To-do

- [ ] 허브 엔티티 정의
- [ ] 허브 엔드포인트 정의
- [ ] 허브 생성 로직 구현
- [ ] 허브 생성 테스트 코드 작성
- [ ] 허브 더미 데이터 생성

## Related issues

Related to: #이슈번호
