### ISSUE TITLE
[Feat/hub-service] 허브 삭제 기능 개발

### ISSUE THREAD

**Issue by Hut234** [Sparta-mosaic/msa-mosaic#4]
## Description
- 허브 삭제 기능 개발

## To-do

- [x] 허브 삭제 엔드포인트 정의
- [x] 허브 삭제 로직 구현
- [x] 허브 삭제 테스트 코드 작성

## Related issues

Related to: #이슈번호
