### ISSUE TITLE
[Feat/hub-service] 허브 조회 기능 개발

### ISSUE THREAD

**Issue by Hut234** [Sparta-mosaic/msa-mosaic#5]
## Description
- 허브 조회 기능 개발

## To-do

- [x] 허브 (단건, 서치) 조회 엔드포인트 정의
- [x] 허브 (단건, 서치) 조회 로직 구현
- [x] 허브 (단건, 서치) 조회 테스트 코드 작성

## Related issues

Related to: #이슈번호
